ci:
  skip: [pylint]

repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: flake8
        args: [--config=.flake8]
  - repo: https://github.com/PyCQA/isort
    rev: 5.5.2
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--safe, --quiet, --line-length=120]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        "types": [python]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
        additional_dependencies: []
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
        exclude: "tests/cassettes/"
