language: python

jobs:
  fast_finish: true
  include:
    - name:  "Python 3.6 on Xenial Linux"
      dist: xenial
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      dist: xenial
      python: 3.7
    - name: "Python 3.8 on Xenial Linux"
      dist: xenial
      python: 3.8
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
  allow_failures:
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows

install:
  - pip3 install --editable ".[test]"
script:
  - python3 -m pytest . --cov=centralized_pre_commit_conf --cov-report html
after_success:
  - coveralls
