
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='centralized_pre_commit_conf',
    version='0.1.0',
    description='Makes it possible to easily install and update pre-commit hooks, and to centralize the configuration files of your tools.',
    packages=['centralized_pre_commit_conf'],
    package_dir={"": "."},
    package_data={"centralized_pre_commit_conf": ["*.cfg", "*.yaml"]},
    install_requires=['setuptools>=45.1', 'wheel>=0.34'],
)
