repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: flake8
        args: [--config=.flake8]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
        - id: pylint
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      args: [--line-length=120]
